name: udschallengeapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  dotenv: ^2.0.0
  scroll_to_index: ^1.0.6
  intl: ^0.16.1
  material_design_icons_flutter: ^4.0.5345
  encrypt: 4.0.0
  firebase_database: ^3.1.6
  toast: ^0.1.5
  firebase_auth: ^0.16.1
  dio: ^3.0.9
  rxdart: ^0.24.1
  bloc_pattern: ^2.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  assets:
    - assets/

# slidy scripts: slidy run <script name>
scripts:
  dotenv: pub global run dotenv